<html>
<head>
	<title>Greg's page</title>
</head>
<style>

@import url('https://fonts.googleapis.com/css?family=Open+Sans');
body{font-family: 'Open Sans',serif;}
thead {color:green;}
tbody {color:black;}
tfoot {color:red;}

table, th, td {
  border-style: solid; padding: 3px;
}
</style>
<body>



<?php
//phpinfo();
//next example will recieve all messages for specific conversation
$API_KEY= "86SM3M44RYM7JTBHQB3J6NDM4GKKA3SZ";

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api.7shifts.com/v1/time_punches');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

curl_setopt($ch, CURLOPT_USERPWD, '86SM3M44RYM7JTBHQB3J6NDM4GKKA3SZ' . ':' . '');

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);

$decode_result = json_decode( $result, true);
//var_dump($decode_result);
$punches = $decode_result["data"];
//print_r($punches);

foreach($punches as $punch)
{
    $punch_clean[] = $punch["time_punch"]; 
}
print_r($punch_clean[0]['id']);
?>
<table>
	<tbody>
		<thead>
			<th>punch id</th>
			<th>Employee ID</th>
			<th>in</th>
			<th>out</th>
		</thead>
		<?php foreach ($punch_clean as $punch) : ?>
        <tr>
            <td> <?php echo $punch['id']; ?> </td>
			<td> <?php echo $punch['user_id']; ?> </td>
            <td> <?php echo $punch['clocked_in']; ?> </td>
			<td> <?php echo $punch['clocked_out']; ?> </td>
        </tr>
		<?php endforeach; ?>
	</tbody>
</table>
</body>
</html>
